name: 'Apply'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  terraform_AWS:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"
      TF_VAR_my_ip: ${{ secrets.MY_IP }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Clean the runner
    - uses: AutoModality/action-clean@v1

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false

    # Install AWS CLI
    - uses: aws-actions/setup-sam@v2    

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: ./Infra
      run: |
        terraform init -backend-config="backend.hcl"

    # Applies Terraform config
    - name: Terraform Apply AWS
      working-directory: ./Infra
      run: |
        terraform apply -auto-approve
        terraform refresh

    - name: Variables AWS
      working-directory: ./Infra
      run: |
        echo "$(terraform output secret_key)" >> ../Docker/id_rsa
        chmod 0400 ../Docker/id_rsa
        ssh-add ../Docker/id_rsa
        echo "TF_VAR_instance_ip=$(terraform output instance_ip | sed 's/"//g')" >> $GITHUB_ENV
        sleep 60s

    - name: Copy down S3 files
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ env.TF_VAR_instance_ip }}
        username: ubuntu
        port: 22
        envs: AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY, AWS_DEFAULT_REGION
        script: |
          mkdir -p /data/Pal/Saved/SaveGames
          aws s3 cp s3://game-files-maximumpigs/palworld/SaveGames /data/Pal/Saved/SaveGames --recursive
          chmod -R 777 /data

    # - name: Copy game files from S3
    #   run: |
    #     aws s3 cp s3://game-files-maximumpigs/palworld/SaveGames ./SaveGames --recursive

    # - name: Place game files
    #   run: |
    #     scp -r -i ./Docker/id_rsa -o StrictHostKeyChecking=no ./SaveGames/* ubuntu@${{ env.TF_VAR_instance_ip }}:/data/Pal/Saved/SaveGames
    #     rm -r ./SaveGames/*

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init Docker
      working-directory: ./Docker
      run: terraform init -backend-config="backend.hcl"

    # Generates an execution plan for Terraform
    - name: Terraform Apply Docker
      working-directory: ./Docker
      run: terraform apply -auto-approve

    # Gets Terraform state and generates cost using cost.modules.tf
    - name: Terraform Get Cost AWS
      working-directory: ./Infra
      run: 'terraform state pull |  curl -s -X POST -H "Content-Type: application/json" -d @- https://cost.modules.tf/ >> $GITHUB_STEP_SUMMARY'      