name: 'Check'

on:
  pull_request:
  workflow_dispatch:
      
permissions:
  contents: read

jobs:
  terraform:
    name: 'Check'
    uses: Maximumpigs/AWS_Docker_Host/.github/workflows/check.yml@main
    secrets: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      TF_VAR_my_ip: ${{ secrets.MY_IP }}