name: 'Start'

on:
  workflow_dispatch:
    inputs: 
      game:
        description: 'Select Game'
        required: true
        type: choice
        options:
          - palworld
          - enshrouded

  repository_dispatch:
    types: [start]

permissions:
  contents: read

jobs:
  terraform_AWS:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"
      TF_VAR_my_ip: ${{ secrets.MY_IP }}
      TF_VAR_game: ${{ github.event.client_payload.game || github.event.inputs.game}}
      TF_VAR_server_name: "[AU]Bro-${{ github.event.client_payload.game || github.event.inputs.game }}"
      TF_VAR_server_password: ${{ secrets.SERVER_PASSWORD }}
      TF_VAR_discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_wrapper: false 

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: Infra
      run: |
        terraform init \
        -backend-config="backend.hcl" \
        -backend-config="key=state/game_servers/${{ github.ref == 'refs/heads/main' && '' || 'dev/' }}${{ env.TF_VAR_game }}/infra.tfstate"

    # Applies Terraform config
    - name: Terraform Apply AWS
      working-directory: Infra
      run: |
        terraform apply -auto-approve
        terraform refresh

    # Gets Terraform state and generates cost using cost.modules.tf
    - name: Set some environment vars
      working-directory: Infra    
      run: |
        curl -sLO https://raw.githubusercontent.com/antonbabenko/terraform-cost-estimation/master/terraform.jq
        echo "PRICE_JSON=$(terraform state pull |  curl -s -X POST -H "Content-Type: application/json" -d @- https://cost.modules.tf/) >> GITHUB_ENV
        echo "TF_VAR_instance_ip=$(terraform output instance_ip | sed 's/"//g')" >> $GITHUB_ENV           

    - name: Set some summary outputs
      working-directory: Infra
      run: |
        echo ${{env.PRICE_JSON}} >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        terraform output instance_ip >> $GITHUB_STEP_SUMMARY
     
      
    - name: Discord Webhook Action
      if: github.ref == 'refs/heads/main'
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: |
          ${{ env.TF_VAR_game }} server is starting, wait for completion message.

          Server IP: ${{ env.TF_VAR_instance_ip }}
          Server Name: ${{ env.TF_VAR_server_name }}
          Server Password: ${{ env.TF_VAR_server_password }}
          Running Cost: $${{ echo "$PRICE_JSON" | cut -d' ' -f2 | cut -d',' -f1 }} USD p/hour
          
    - name: Prepare key file
      working-directory: Infra
      run: |
        echo "$(terraform output secret_key)" >> ../Docker/id_rsa
        chmod 0400 ../Docker/id_rsa
        sleep 60s

    - name: Copy game files from S3
      run: |
        aws s3 cp s3://game-files-maximumpigs/${{ github.ref == 'refs/heads/main' && '' || 'dev/' }}${{ env.TF_VAR_game }}/ ./${{ env.TF_VAR_game }} --recursive

    - name: Place game files
      run: |
        rsync -ur -e "ssh -o StrictHostKeyChecking=no -i ./Docker/id_rsa" ./${{ env.TF_VAR_game }}/ ubuntu@${{ env.TF_VAR_instance_ip }}:/data/
        ssh ubuntu@${{ env.TF_VAR_instance_ip }} -i Docker/id_rsa -o StrictHostKeyChecking=no 'sudo chmod -R 777 /data'
        rm -r ${{ env.TF_VAR_game }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      working-directory: Docker
      run: |
        terraform init \
        -backend-config="backend.hcl" \
        -backend-config="key=state/game_servers/${{ github.ref == 'refs/heads/main' && '' || 'dev/' }}${{ env.TF_VAR_game }}/docker.tfstate"

    # Generates an execution plan for Terraform
    - name: Terraform Apply Docker
      working-directory: Docker
      run: |
        terraform apply -auto-approve

    # Removes Github Runner access
    - name: Terraform Apply AWS
      working-directory: Infra
      run: |
        terraform apply -auto-approve \
        -var='runner_access_enabled=false'