name: 'Test'

on:
  workflow_dispatch:
    inputs: 
      game:
        description: 'Select Game'
        required: true
        type: choice
        options:
          - palworld
          - enshrouded

  repository_dispatch:
    types: [test]

permissions:
  contents: read

jobs:
  terraform_AWS:
    runs-on: ubuntu-latest
    env: 
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
      AWS_DEFAULT_REGION: "ap-southeast-2"
      TF_VAR_my_ip: ${{ secrets.MY_IP }}
      TF_VAR_game: ${{ github.event.client_payload.game || github.event.inputs.game}}
      TF_VAR_server_name: "[AU]Bro-${{ github.event.client_payload.game || github.event.inputs.game }}"
      TF_VAR_server_password: ${{ secrets.SERVER_PASSWORD }}
      TF_VAR_discord_webhook: ${{ secrets.DISCORD_WEBHOOK }}
      TF_VAR_instance_ip: "123.123.123.123"
      TF_VAR_vm_size: ""
      PRICE: "0.05"      

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:

    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    - name: Discord Webhook Action
      uses: tsickert/discord-webhook@v5.3.0
      with:
        webhook-url: ${{ secrets.DISCORD_WEBHOOK }}
        content: |
          ${{ env.TF_VAR_game }} server is starting, wait for completion message.

          Server IP: ${{ env.TF_VAR_instance_ip }}
          Server Name: ${{ env.TF_VAR_server_name }}
          Server Password: ${{ env.TF_VAR_server_password }}
          Running Cost: $${{ env.PRICE }} USD p/hour